[package]
name = "magma-ipc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wayland-client = "0.30.1"
wayland-scanner = "0.30.0"
wayland-backend = "0.1.2"
