name: Nix Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  nix-build:
    name: Nix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Setup magic-nix-cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build
        run: nix build 
